'use client'

import { motion } from 'framer-motion'
import {
  FiShield,
  FiCheck,
  FiFileText,
  FiLock,
  FiUsers,
  FiBookOpen
} from 'react-icons/fi'

const LegalCompliance = () => {
  const complianceFeatures = [
    {
      rule: 'Fed. R. Evid. 901',
      title: 'Authentication Requirements',
      icon: FiShield,
      description: 'Blockchain verification provides admissible proof of authenticity under Rule 901(b)(9) - "evidence about a process or system and showing it produces an accurate result."',
      implementation: 'Cryptographic hash generation with immutable blockchain storage ensures evidence integrity'
    },
    {
      rule: 'Fed. R. Evid. 902',
      title: 'Self-Authentication',
      icon: FiLock,
      description: 'Digital evidence can be self-authenticating when accompanied by a certificate under Rule 902(13) for "certified records generated by an electronic process or system."',
      implementation: 'Automated certificate generation with complete metadata and verification trail'
    },
    {
      rule: 'Fed. R. Evid. 1003',
      title: 'Best Evidence Rule',
      icon: FiFileText,
      description: 'Original digital files are acceptable as originals under the Best Evidence Rule for electronically stored information.',
      implementation: 'Immutable PDF generation maintains original quality and metadata integrity'
    },
    {
      rule: 'Fed. R. Civ. P. 26(f)',
      title: 'Discovery Planning',
      icon: FiUsers,
      description: 'Parties must consider issues relating to disclosure and discovery of electronically stored information during meet-and-confer.',
      implementation: 'Built-in export functionality with litigation hold capabilities and chain of custody'
    }
  ]

  const certifications = [
    {
      icon: FiCheck,
      title: 'Court Admissibility',
      status: 'Validated',
      description: 'Evidence format meets all technical requirements for admissibility in federal and state courts.'
    },
    {
      icon: FiBookOpen,
      title: 'Legal Standards',
      status: 'Compliant',
      description: 'Adheres to ABA Model Rules of Professional Conduct for technology competence.'
    },
    {
      icon: FiCheck,
      title: 'Chain of Custody',
      status: 'Automated',
      description: 'Maintains complete audit trail from capture to presentation with immutable timestamps.'
    },
    {
      icon: FiShield,
      title: 'Due Process',
      status: 'Protected',
      description: 'Preserves fundamental fairness requirements with transparent verification process.'
    }
  ]

  const useCases = [
    {
      area: 'Intellectual Property',
      examples: ['Trademark infringement documentation', 'Copyright violation evidence', 'Patent prior art capture']
    },
    {
      area: 'Employment Law',
      examples: ['Workplace harassment documentation', 'Policy violation evidence', 'Social media misconduct']
    },
    {
      area: 'Corporate Litigation',
      examples: ['Contract breach evidence', 'Financial statement capture', 'Regulatory compliance documentation']
    },
    {
      area: 'Family Law',
      examples: ['Social media evidence', 'Asset documentation', 'Communication records']
    }
  ]

  return (
    <section className="py-24 bg-legal-texture">
      <div className="container-max-width section-padding">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className="text-center space-y-4 mb-16"
        >
          <h2 className="text-3xl lg:text-5xl font-bold text-gray-900">
            Legal Standards & Compliance
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Designed to meet established legal standards for evidence authentication.
            Built with court admissibility requirements in focus.
          </p>
        </motion.div>

        {/* Federal Rules Compliance */}
        <div className="space-y-8 mb-20">
          <h3 className="text-2xl font-bold text-gray-900 text-center mb-12">Evidence Authentication Standards</h3>
          <div className="grid lg:grid-cols-2 gap-8">
            {complianceFeatures.map((feature, index) => (
              <motion.div
                key={feature.rule}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-white rounded-lg border border-gray-200 p-6 hover:shadow-lg transition-shadow duration-300"
              >
                <div className="flex items-start space-x-4">
                  <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center flex-shrink-0">
                    <feature.icon className="w-6 h-6 text-primary-600" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-2">
                      <span className="text-sm font-mono text-primary-600 bg-primary-50 px-2 py-1 rounded">
                        {feature.rule}
                      </span>
                      <h4 className="font-bold text-gray-900">{feature.title}</h4>
                    </div>
                    <p className="text-gray-600 mb-4 italic">{feature.description}</p>
                    <div className="bg-gray-50 rounded p-3">
                      <p className="text-sm text-gray-700 font-medium">Implementation:</p>
                      <p className="text-sm text-gray-600">{feature.implementation}</p>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Certifications */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          viewport={{ once: true }}
          className="bg-gray-900 rounded-2xl p-8 text-white mb-20"
        >
          <h3 className="text-2xl font-bold mb-8 text-center">Professional Certifications</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {certifications.map((cert) => (
              <div key={cert.title} className="text-center space-y-4">
                <div className="w-16 h-16 bg-primary-600 rounded-full flex items-center justify-center mx-auto">
                  <cert.icon className="w-8 h-8 text-white" />
                </div>
                <div>
                  <h4 className="font-bold text-white mb-1">{cert.title}</h4>
                  <div className="text-primary-400 text-sm font-medium mb-2">{cert.status}</div>
                  <p className="text-gray-300 text-sm">{cert.description}</p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Use Cases */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
          viewport={{ once: true }}
          className="space-y-8"
        >
          <h3 className="text-2xl font-bold text-gray-900 text-center">Legal Practice Areas</h3>
          <div className="grid md:grid-cols-2 gap-6">
            {useCases.map((useCase, index) => (
              <div key={useCase.area} className="bg-white rounded-lg border border-gray-200 p-6">
                <h4 className="font-bold text-gray-900 mb-4">{useCase.area}</h4>
                <ul className="space-y-2">
                  {useCase.examples.map((example) => (
                    <li key={example} className="text-gray-600 flex items-center">
                      <span className="w-1.5 h-1.5 bg-primary-600 rounded-full mr-3 flex-shrink-0"></span>
                      {example}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Legal Notice */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.5 }}
          viewport={{ once: true }}
          className="mt-16 p-6 bg-blue-50 rounded-lg border border-blue-200"
        >
          <div className="flex items-start space-x-3">
            <FiBookOpen className="w-6 h-6 text-blue-600 flex-shrink-0 mt-1" />
            <div>
              <h4 className="font-semibold text-blue-900 mb-2">Legal Notice</h4>
              <p className="text-blue-800 text-sm leading-relaxed">
                ProofVault is designed to support legal professionals in evidence collection and management.
                While our system meets technical requirements for court admissibility, users should consult
                with legal counsel regarding specific jurisdictional requirements and case-specific considerations.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  )
}

export default LegalCompliance