on: push

jobs:
  hydra-script-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Uninstall current Docker version
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Verify Docker installation
        run: docker --version

      - name: Install dependencies (jq, yq, ansible)
        shell: bash
        run: |
          # Install jq
          sudo apt install -y jq
          
          # Install yq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          # Install Ansible
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Load config file
        shell: bash
        env:
          GITHUB_PAT: ${{ secrets.TOKEN }}
        run: |
          echo "Loading GitHub token into euclid.json..."
          
          # First check if we can access the default GITHUB_TOKEN
          if [ -n "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Default GITHUB_TOKEN is accessible"
          fi
          
          # Check if TOKEN secret is available via env variable
          if [ -z "$GITHUB_PAT" ]; then
            echo "ERROR: TOKEN secret is not accessible!"
            echo ""
            echo "Please ensure you have added a repository secret (not variable) named 'TOKEN'"
            echo "Go to: Settings → Secrets and variables → Actions → Secrets tab → New repository secret"
            echo ""
            echo "For now, trying with the default GITHUB_TOKEN..."
            # Use the default GITHUB_TOKEN as fallback
            GITHUB_PAT="${{ secrets.GITHUB_TOKEN }}"
          else
            echo "TOKEN secret found via environment variable"
          fi
          
          echo "Updating euclid.json with token..."
          contents="$(jq --arg GITHUB_TOKEN "$GITHUB_PAT" '.github_token = $GITHUB_TOKEN' euclid.json)"
          echo -E "${contents}" > euclid.json
          
          echo "Verifying token was set (showing length):"
          token_length=$(jq -r '.github_token | length' euclid.json)
          echo "Token length: $token_length characters"
          
          if [ "$token_length" -lt 10 ]; then
            echo "ERROR: Token appears to be too short or not set properly"
            exit 1
          fi
          
      - name: Run steps
        shell: bash
        run: |
          echo "Installing CARGO"
          curl https://sh.rustup.rs -sSf | sh -s -- -y 
          echo "Cargo Installed"
          
          source $HOME/.cargo/env

          echo "Installing ARGC"
          cargo install argc
          echo "ARGC Installed"
          
          echo "Installing Scala"
          curl -fL https://github.com/coursier/coursier/releases/download/v2.1.0/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup -y
          echo "Scala Installed"
          
          source ~/.profile
          
          echo "Installing Giter"
          cs install giter8
          echo "Gitter Installed"
          
          # Change to scripts directory for all hydra operations
          cd scripts/
          
          # Skip install since project already has framework
          # Project is already in the correct structure: source/project/ProofVault
          
          # Check if we're in GitHub Actions CI environment
          if [ -n "$GITHUB_ACTIONS" ]; then
            echo "Running in GitHub Actions - checking for existing build"
            # Clean up any existing builds to avoid tag conflicts
            docker image prune -f || true
            # Remove any existing images with our tag
            docker rmi $(docker images -q metagraph-base-image:2.8.1) 2>/dev/null || true
            docker rmi $(docker images -q metagraph-ubuntu:2.8.1) 2>/dev/null || true
          fi
          
          # Build the project
          ./hydra build
          
          # Start and test
          ./hydra start-genesis
          
          # Stop and cleanup
          ./hydra stop
          
          ./hydra destroy