name: Test Secrets Access

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-secrets.yml'

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test if any secrets are accessible
        run: |
          echo "Testing secret access..."
          
          # Test TOKEN
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "❌ TOKEN secret is NOT accessible"
          else
            echo "✅ TOKEN secret is accessible"
          fi
          
          # Test GITHUB_TOKEN (default token)
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "❌ GITHUB_TOKEN secret is NOT accessible"
          else
            echo "✅ GITHUB_TOKEN secret is accessible"
          fi
          
          # List all secrets (names only, not values)
          echo ""
          echo "Checking various secret formats:"
          echo "secrets.TOKEN empty check: ${{ secrets.TOKEN == '' }}"
          echo "secrets.TOKEN null check: ${{ secrets.TOKEN == null }}"
          
          # Try different approaches
          echo ""
          echo "Alternative checks:"
          TOKEN_VAL="${{ secrets.TOKEN }}"
          if [ -z "$TOKEN_VAL" ]; then
            echo "Variable assignment check: TOKEN is empty"
          else
            echo "Variable assignment check: TOKEN has value"
          fi